package:
  name: tmap
  version: 1.0.6

build:
  number: 0
  binary_relocation: False # [osx]
  skip: True  # [py<35]

extra:
  - conda-forge

source:
  path: ..
  
requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - ninja  # [win]
    - vs2019_win-64 # [win]
    - cmake
    - python {{ python }}
    - setuptools
    - pybind11
    - ogdf
    - scipy
    - attrs
  host:
    - vs2015_runtime # [win]
    - llvm-openmp # [osx]
    - python
    - pip
    - ogdf
    - python-annoy
    - scipy
    - attrs
  run:
    - vs2015_runtime # [win]
    - llvm-openmp # [osx]
    - python
    - ogdf
    - python-annoy
    - scipy
    - attrs

test:
  requires:
    - pytest
  imports:
    - tmap
  source_files:
  - tests/test_layout.py
  - tests/test_lsh_forest.py
  - tests/test_minhash.py
  commands:
    - pytest

about:
  home: http://gdb.tools
  license: MIT
  # license_file: LICENSE
  summary: 'A Python package for visualizing large, high-dimensional data sets.'
  description: 'A Python package for visualizing large, high-dimensional data sets.'
  dev_url: https://github.com/reymondgroup/mstmap

extra:
    recipe-maintainers:
        - daenuprobst
